### Configuration File (config.yaml)

motor_params:
  L_d: 0.01  # d轴电感 (H)
  L_q: 0.01  # q轴电感 (H)
  R_s: 0.01  # 定子电阻 (Ohm)
  psi_f: 0.1  # 永磁磁链 (Wb)

data_params:
  num_samples: 1000  # 数据样本数量

training_params:
  learning_rate: 0.001
  epochs: 500
  batch_size: 64